name: Node.js CI

# Elige los eventos que disparan la ejecución
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    # Descarga el código del repositorio en el servidor de GitHub
    - name: Clonar repositorio
      uses: actions/checkout@v5
      

    # Configura el entorno con la versión estable de Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20
        cache-dependency-path: ./mi-app-node/
        cache: 'npm' # Optimiza futuras ejecuciones guardando dependencias en caché


    - name: Set up QEMU for demo Docker
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx for demo 
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERTOKEN1 }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          tags: hanimich01containers/nodeapp1