name: Node.js CI

# Elige los eventos que disparan la ejecución
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted, linux

    steps:
    # Descarga el código del repositorio en el servidor de GitHub
    - name: Clonar repositorio
      uses: actions/checkout@v5
      

    # Configura el entorno con la versión estable de Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20
        cache-dependency-path: ./mi-app-node/
        cache: 'npm' # Optimiza futuras ejecuciones guardando dependencias en caché

    # Instala las dependencias necesarias (si existieran en package.json)
    - name: Instalar dependencias
      run: npm ci

    # Ejecuta el script de pruebas configurado
    - name: Ejecutar pruebas
      run: npm test